### ISSUE TITLE
react hmr example

### ISSUE THREAD

**Issue by dKab** [shellscape/koa-webpack#25] opened 2017-02-17 15:26 UTC
I'd love to see working example of koa-webpack with webpack 2 and react-hot-loader3

**Comment by cmoad** [comment] 2017-02-23 20:45
Created #30 because I also wanted to see this.

**Comment by dKab** [comment] 2017-02-23 22:54
@cmoad I managed to get it working in my setup. You may take a look at it here: https://github.com/dKab/recipy-book

**Comment by shellscape** [comment] 2017-02-23 23:43
@dKab wonderful! could I link to your project in koa-webpack's README?

**Comment by dKab** [comment] 2017-02-23 23:48
@shellscape sure, no problem. Thanks for the package by the way.

**Comment by cmoad** [comment] 2017-02-24 03:27
Perhaps I'm misunderstanding, but I don't see that you are hot reloading the server code. I'm trying to setup a project with only server code (no react). I also see in your readme:

> Hot reloading is enabled. Client bundle will be recompiled with every change, however server bundle won't (HMR wouldn't work if server was recompiled on every change).

**Comment by dKab** [comment] 2017-02-24 09:07
>but I don't see that you are hot reloading the server code
Oops. Sorry. I din't know hmr can can be applied to server code as well as to client.

**Comment by cmoad** [comment] 2017-02-24 14:40
Perhaps it can't and that's why I am struggling.

**Comment by dKab** [comment] 2017-02-24 15:14
But I don't I think I grasp the concept of hmr on the server. On the client it's pretty clear - bundle is updated on the fly and thus you don't have to reload the browser to see changes. On the other hand what would be the idea of hmr on the server side? I mean why the solution when you track changes in source files and recompile server bundle and restart node with new bundle wouldn't work for you? 

To achieve this you could (assuming you use webpack for budling server code) start webpack in watch mode and use something like nodemon to restart your server script when bundle is changed. 

Or am I missing something?

**Comment by shellscape** [comment] 2017-02-24 15:36
From webpack-hot-middleware's [readme](https://github.com/glenjamin/webpack-hot-middleware#webpack-hot-middleware):

> This module is only concerned with the mechanisms to connect a browser client to a webpack server & receive updates. It will subscribe to changes from the server and execute those changes using webpack's HMR api. 

That links to the [HMR API](http://webpack.github.io/docs/hot-module-replacement-with-webpack.html) which to me reads that it's only concerned with client-side things, as that's webpack's targeted focus.

The suggestion by @dKab sounds like a winner. But server-side module reloading may be out of scope for this module, given the client-side focus. It sounds like something that needs to work externally in conjunction with koa-webpack.

**Comment by bryanlarsen** [comment] 2017-09-27 10:08
Note: the linked example abandoned koa-webpack, claiming it was broken:  https://github.com/dKab/recipe-book/commit/701deac0a7d5f03cb99eaa485df3e601d0c2bbe4

**Comment by shellscape** [comment] 2017-09-27 13:31
@bryanlarsen that's humorous, but thank you for sharing for the benefit of others. closing this issue as it's pretty stale. we'll welcome contributed examples for different platforms (like React) but it's not something that's a priority at the moment.

**Closed by shellscape** 2017-09-27 13:31 UTC

**Comment by damianobarbati** [comment] 2017-11-25 11:33
Was anyone able to reproduce a public working example with react?

**Comment by mrchief** [comment] 2018-01-19 16:07
I have React hot loading working with `"koa-webpack": "^1.0.0"`. `"koa-webpack": "^2.0.3",` seems to break it and I haven't found the missing link yet. Probably I'll go back to using v1.
