### ISSUE TITLE
Can't set headers after they are sent

### ISSUE THREAD

**Issue by christensson** [shellscape/koa-webpack#2] opened 2016-10-27 13:00 UTC
I experience the same error as in https://github.com/leecade/koa-webpack-middleware/issues/2, same procedure to reproduce. Reload page before webpack build has finished.

**Comment by shellscape** [comment] 2016-10-27 14:42
could you provide a small sample of what your setup looks like, so I can try and reproduce the same environment?

**Comment by christensson** [comment] 2016-10-27 18:06
Try to configure a koa2 application to use webpack with webpack configured to rebuild when any client-side code changes, but don't configure the automatic reload functionality. This is my koa-webpack config:
~~~
const koaWebpack = require("koa-webpack");
app.use(koaWebpack({
  config: require(pathToWebpack.config.js),
    dev: {
      stats: false
    },
    hot: {}
}));
~~~

This is my webpack plugin config:
~~~
plugins: [
  new webpack.DefinePlugin({
    "process.env.NODE_ENV": JSON.stringify(process.env.NODE_ENV)
  }),
  new webpack.optimize.OccurrenceOrderPlugin()
  new webpack.NoErrorsPlugin(),
  new webpack.LoaderOptionsPlugin({
    debug: true
  })
]
~~~

To reproduce, start server and hit reload in client before the webpack build is finished. That will trigger the fault. The fault will also trigger if you do a small code-change and then after that do a page reload. If you're not fast enough (the webpack build is too fast), this can probably triggered by touch and wget/curl:
`touch some/file/that/triggers/webpack/rebuild && wget http://localhost:8080/js/bundle.js > /dev/null`

This triggers the fault for me:
~~~
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at Object.set (src/lib/web/node_modules/koa/lib/response.js:437:16)
    at Object.proto.(anonymous function) [as set] (src/lib/web/node_modules/delegates/index.js:40:31)
    at handleRangeHeaders (src/lib/web/node_modules/webpack-dev-middleware/middleware.js:165:7)
    at processRequest (src/lib/web/node_modules/webpack-dev-middleware/middleware.js:241:14)
    at continueBecauseBundleAvailable (src/lib/web/node_modules/webpack-dev-middleware/middleware.js:94:5)
    at Array.forEach (native)
    at src/lib/web/node_modules/webpack-dev-middleware/middleware.js:93:8
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at Object.set (src/lib/web/node_modules/koa/lib/response.js:437:16)
    at Object.proto.(anonymous function) [as set] (src/lib/web/node_modules/delegates/index.js:40:31)
    at handleRangeHeaders (src/lib/web/node_modules/webpack-dev-middleware/middleware.js:165:7)
    at processRequest (src/lib/web/node_modules/webpack-dev-middleware/middleware.js:241:14)
    at continueBecauseBundleAvailable (src/lib/web/node_modules/webpack-dev-middleware/middleware.js:94:5)
    at Array.forEach (native)
    at src/lib/web/node_modules/webpack-dev-middleware/middleware.js:93:8
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
~~~

**Comment by shellscape** [comment] 2016-10-27 19:30
This looks like more of a race condition in webpack-dev-middleware at first glance. https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L221

I'll keep looking at it, but it'd probably be worth mentioning on that project.

**Comment by wtgtybhertgeghgtwtg** [comment] 2016-10-27 20:07
The problem is that you are [trying to `await` it](https://github.com/shellscape/koa-webpack/blob/master/index.js#L13).  `dev` returns `undefined`.  The function resolves immediately.

**Comment by shellscape** [comment] 2016-10-27 20:20
There's that. And also that the call to `compile` has a callback that doesn't do squat. https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L156

I think we're going to need an update to webpack-dev-middleware to know when the compile has finished. Only then are we going to be able to accurately wait for it.

**Comment by wtgtybhertgeghgtwtg** [comment] 2016-10-27 20:40
There's already [a proposal Koa support](https://github.com/webpack/webpack-dev-middleware/pull/111) there, although it's for `koa@1`.  Changing `webpack-dev-middleware` to use promises so this library can do that may just complicate things.

**Comment by shellscape** [comment] 2016-10-27 20:49
@wtgtybhertgeghgtwtg but implementing an error-first callback is relatively harmless, and could then be used with thunks and wrapped for Promises. That's what I'm hoping they'll do. If they take a while to respond I'll fork and work up a PR. Looks like they're waiting on a rewrite in https://github.com/webpack/webpack-dev-middleware/pull/140 before they make any moves on koa support.

**Comment by wtgtybhertgeghgtwtg** [comment] 2016-10-27 21:02
It may or may not be harmless, but for its intended use as `express` middleware, it is also useless.  The sole use case of returning a callback would be `koa-webpack`, so it could provide functionality that `webpack-dev-middleware` is planned to provide.  So it is a temporary use case.
I would propose integrating `webpack-dev-middleware` instead of forking it.

**Comment by shellscape** [comment] 2016-10-27 21:08
integrating it would be akin to forking it - six of one, half dozen of another. and I disagree that it'd be useless - any system that relied on knowing when a thing was done before moving onto the next task would benefit.

**Comment by wtgtybhertgeghgtwtg** [comment] 2016-10-27 21:19
Integrating and forking would be different.  If you fork `webpack-dev-middleware`, you would have another package, let's call it `webpack-dev-middleware-with-callback`, and this package, `koa-webpack`, which would just wrap `webpack-dev-middleware-with-callback`.  Both packages would need to be tested and maintained, even though `webpack-dev-middleware-with-callback` would only exist to be wrapped by `koa-webpack`.  So you would be maintaining `express` middleware that exposes a callback so that it can be wrapped as `koa` middleware, instead of just maintaining `koa` middleware.

**Comment by shellscape** [comment] 2016-10-27 21:23
yeah, not going to argue the semantics there so let's put that back on the shelf. but I will state that I'm not going to integrate the module into this one.

might be able to do something with the compiler plugin methods `done` and `failed` though; https://github.com/webpack/docs/wiki/plugins

**Comment by shellscape** [comment] 2016-10-27 21:45
@christensson install `koa-webpack@0.1.7-test` and let me know if that resolves the issues. short on time and ran a quick test using the console and it seemed to wait properly (and I also don't have a project big enough on hand that there'd be a delay to reproduce the issue).

**Comment by lostpebble** [comment] 2016-10-28 10:12
Hi @christensson. The test version is not working for me unfortunately. As in it never completes a server response, even when I wait for webpack to finish compiling before loading the page. Or on the off chance it does, none of my webpack resources get resolved such as `bundle.js` etc.

I'm using `webpack@1.13.3`

The way I'm using it:
```
const devConfig = require('../../../webpack.config.client');

app.use(middleware({
    config: devConfig,
    dev: {
      noInfo: true,
      publicPath: devConfig.output.publicPath,
    },
  }));
```

It is a decent sized project, and webpack takes around 7-10s to compile usually.

I placed some logging before and after the webpack middleware to get an idea what was getting stuck where, and it appears that for any resources which need to be resolved by webpack such as `bundle.js` and some images etc. on the down stream (not completely sure of the terminology, but I mean the first part of the request stream before it comes back again) it never gets past webpack middleware.

**Comment by christensson** [comment] 2016-10-28 10:28
@shellscape koa-webpack@0.1.7-test doesn't work. It does not crash with the "Can't set headers after they are sent" error, but something is not right in the way requests are handled.

For example if I reload my page with the bundle.js already built and valid, then the dev-end function will be called, but the promise will not be resolved since the "done" plugin event will not be called (the bundle was never dirty). If I hit reload and then invalidates the bundle a couple of times (one time is not always enough) it works.

So as a summary, I think the case with a valid bundle is not handled since plugin "done" will not be called in that case and the promise will not be resolved. Does it make sense?

**Comment by shellscape** [comment] 2016-10-28 16:11
@lostpebble this module has a peerDependency on webpack@beta, which is 2.1.x+. I cannot promise that it'll work with anything under that version. https://github.com/shellscape/koa-webpack/blob/master/package.json#L26

@christensson good catch. I'll see if I can put something in place to handle that.

**Comment by shellscape** [comment] 2016-10-28 18:33
trying to figure out how to query the current state of the `compiler` only then will I know if it's currently in a state of compiling or not.

**Comment by shellscape** [comment] 2016-10-28 18:51
@christensson published koa-webpack@0.1.7-test2 just now. I ran some tests here and it caught both states (pre-build and hot reload from change). let me know how it works out for you. @lostpebble this may work for you as well, but I can't guarantee anything for webpack@1.x

**Comment by lostpebble** [comment] 2016-10-29 11:38
@shellscape I've upgraded my webpack to `2.1.0-beta.25` now, and tried the new test version. The problem is still around for me though. It appears that any resources that are requested from Webpack now are just returned 404 while webpack is compiling, and when it finishes it gives the `Error: Can't set headers after they are sent.` It seems like a tough one, thanks for your efforts in trying to work it out!

**Comment by shellscape** [comment] 2016-10-29 13:05
@lostpebble hm on my end everything waits for webpack correctly with that test version. someone that can reproduce the problem is going to have to step in with a fix then I'm afraid.

**Comment by marr** [comment] 2016-10-30 13:32
I am recieving the same `Can't set headers after they are sent.` error. I'll see about trying to create a boilerplate project that reproduces the issue.

**Comment by christensson** [comment] 2016-10-31 08:39
@shellscape I've tested koa-webpack@0.1.7-test2 and I'm sad to say that it doesn't catch any of the two cases for me. I did my own efforts trying to solve this, and I found that the webpack-dev-middleware function waitUntilValid can be used. See pull-request #3 .

**Comment by shellscape** [comment] 2016-10-31 11:30
@christensson this module pretty clearly requires webpack@2.1.x (as I've told others and is outlined in the README), so you might want to update. I'll check out your PR and comment there.

**Comment by christensson** [comment] 2016-10-31 11:33
@shellscape I'm running with webpack@2.1.0-beta.25 and have done so all the time.

**Comment by shellscape** [comment] 2016-10-31 11:34
It's early 😄 I misread "koa-webpack@0.1.7-test2" as "webpack@0.1.7-test2". Shall return after coffee!

**Comment by shellscape** [comment] 2016-10-31 16:08
published v0.1.7

**Closed** 2016-10-31 16:07 UTC

**Comment by lemieux** [comment] 2016-11-05 01:00
Hi, I had the whole set of problem this thread is about (404 when assets was not built yet, etc.). v0.1.7 solved the initial build problem but then once the asset is built, my whole app is just hanging  when I request the asset again (refreshing the page for instance). I tried to dig in the code to find out where it happens with no luck.

Does this ring a bell?

**Comment by lemieux** [comment] 2016-11-05 01:16
Uh, I think I have the same problem as in #4.

**Comment by shellscape** [comment] 2016-11-05 02:25
@lemieux give version 0.1.8 a shot.

**Comment by lbdremy** [comment] 2017-03-28 13:35
https://github.com/sigfox/webpack-dev-middleware/commit/3edb0d7fa7e84f7e38a67e3592bd25eff87d2843

This fix the issue, the issue is `next()` is called asynchronously in one case but not return, in this case undefined is returned causing koa to move up into the stack of middleware and send the response, meanwhile the next() function is called causing the next middleware to be called and sending a response of its own throwing the error "Can't set headers after they are sent". I'm not sure if this kind of patch will be accepted in the webpack-dev-middleware. Wrapping the code where next is called into a Promise does the job to chain things correctly.

**Comment by shellscape** [comment] 2017-03-28 14:31
@lbdremy thanks for jumping in the conversation! my apologies, but I'm having some trouble figuring out what you're trying to say. here's what I think you're saying, please tell me if I'm correct or way off :

> the linked commit fixes the problem in webpack-dev-middleware, but you're not sure if they'll merge your fix

I'm not seeing this problem in koa-webpack since version 0.1.8, but if you are, is there anything we can do in koa-webpack to fix the issue in your use-case?

**Comment by lbdremy** [comment] 2017-03-28 15:02
The error is not because there is an issue in koa-webpack but because webpack-dev-middleware calls `next()` while `undefined` has been already returned to koa-webpack. See here https://github.com/sigfox/webpack-dev-middleware/commit/3edb0d7fa7e84f7e38a67e3592bd25eff87d2843#commitcomment-21521391

**Comment by shellscape** [comment] 2017-03-28 15:31
@lbdremy cool, thanks. if you open a PR on webpack-dev-middleware, I can try and have the webpack maintainers take a look at it. they're good folks.

**Comment by nahtnam** [comment] 2017-04-16 20:49
Same issue here. Any workarounds, or do I just have to wait?

**Comment by ahlusar1989** [comment] 2017-05-05 14:56
@nahtnam Do you mind sharing with your workaround with nodemon? I am using nodemon as well and would really appreciate some insight into this scenario:  "**nodemon didnt restart the server after a change in the assets**."

**Comment by nahtnam** [comment] 2017-05-05 16:15
@ahlusar1989 You can do `nodemon index.js --ignore public/assets --ignore app/assets`. You should ignore both the folder with the assets are and where the assets are compiled.

I personally have moved away from webpack-dev-server. I spawn two processes, one for nodemon and one for webpack. That way when my nodemon server restarts, webpack doesnt recompile. It's a much faster system.

**Comment by ahlusar1989** [comment] 2017-05-05 19:04
Thanks for the feedback @nahtnam I'll be sure to do that.
